name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: .github/renovate-global.js
          token: "${{ steps.get_token.outputs.token }}"
        env:
          RENOVATE_PLATFORM_COMMIT: "true"
